### ISSUE TITLE
Choosing a different currency after generating a key does not reset the UI

### ISSUE THREAD

**Issue by richardtop** [onmyway133/AddressGenerator#1]
Steps to reproduce:
1. Pick a currency
2. Generate a key
3. Pick a different currency

4. The currency title is changes, however the old address is being shown, which is misleading.

**Comment by onmyway133** [comment]
@richardtop Hi, and yeah, I was aware of that.  I can make a fix

**Comment by onmyway133** [comment]
@richardtop Hi, you can now check https://github.com/onmyway133/AddressGenerator/releases/tag/1.0.1
